version: "3.7"
services:
  microservice:
    image: payara/micro:6.2022.2-jdk17
    container_name: microservice
    ports:
      - "8080:8080" # HTTP listener
      - "9009:9009" # Java debugger
    volumes:
      - "./build/libs:/opt/payara/deployments"
    networks:
      - web
networks:
  web:
